name: Tests
on:
  - push
  - pull_request

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python: '3.7'
            toxenv: 'py'
          - python: '3.8'
            toxenv: 'py'
          - python: '3.9'
            toxenv: 'py'
          - python: '3.10'
            toxenv: 'py'
          - python: '3.10'
            toxenv: 'setup'
          - python: '3.10'
            toxenv: 'flake8'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade setuptools pip tox
    - name: Test with tox
      run: tox -e ${{ matrix.toxenv }}
